services:
  jira:
    image: atlassian/jira-software
    container_name: jira
    ports:
      - "8080:8080"
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/jiradb
      - ATL_JDBC_USER=jira
      - ATL_JDBC_PASSWORD=jira
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_DB_TYPE=postgres72
      - JVM_MAXIMUM_MEMORY=2048m
      - JVM_MINIMUM_MEMORY=1024m
    volumes:
      - jira-data:/var/atlassian/application-data/jira
    depends_on:
      - postgres
    networks:
      - jira-network

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=jira
      - POSTGRES_DB=jiradb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jira-network

volumes:
  jira-data:
  postgres-data:

networks:
  jira-network:
    driver: bridge
